name: Build Mono

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Mono version to build (e.g., mono-6.12.0.182)'
        required: false
        default: 'mono-6.12.0.182'
  push:
    branches: [main]
    paths:
      - 'MONO_VERSION'

env:
  MONO_VERSION: ${{ github.event.inputs.version || 'mono-6.12.0.182' }}

jobs:
  build-mono-linux:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            autoconf \
            libtool \
            automake \
            cmake \
            gettext \
            libglib2.0-dev \
            git

      - name: Clone and build Mono
        run: |
          git clone --depth 1 --branch ${{ env.MONO_VERSION }} https://github.com/mono/mono.git
          cd mono
          ./autogen.sh --prefix=/tmp/mono-install --with-mcs-docs=no
          make -j$(nproc)
          make install

      - name: Package Mono
        run: |
          mkdir -p dist
          cd /tmp/mono-install
          tar -czf $GITHUB_WORKSPACE/dist/mono-linux-x64.tar.gz .

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mono-linux-x64
          path: dist/mono-linux-x64.tar.gz

  build-mono-macos:
    runs-on: macos-12
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          brew install autoconf automake libtool pkg-config cmake gettext

      - name: Clone and build Mono
        run: |
          git clone --depth 1 --branch ${{ env.MONO_VERSION }} https://github.com/mono/mono.git
          cd mono
          ./autogen.sh --prefix=/tmp/mono-install --with-mcs-docs=no
          make -j$(sysctl -n hw.ncpu)
          make install

      - name: Package Mono
        run: |
          mkdir -p dist
          cd /tmp/mono-install
          tar -czf $GITHUB_WORKSPACE/dist/mono-macos-x64.tar.gz .

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mono-macos-x64
          path: dist/mono-macos-x64.tar.gz

  create-mono-release:
    needs: [build-mono-linux, build-mono-macos]
    runs-on: ubuntu-latest
    if: always() && (needs.build-mono-linux.result == 'success' || needs.build-mono-macos.result == 'success')
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Generate release tag
        id: tag
        run: |
          TIMESTAMP=$(date +"%Y%m%d-%H%M%S")
          TAG="mono-${TIMESTAMP}"
          echo "tag=$TAG" >> $GITHUB_OUTPUT
          echo "Generated tag: $TAG"

      - name: Create Mono Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag.outputs.tag }}
          name: "Mono Build ${{ steps.tag.outputs.tag }}"
          body: |
            ## Mono Distribution
            
            **Mono Version:** ${{ env.MONO_VERSION }}
            
            ### 利用可能なプラットフォーム
            - Linux x64
            - macOS x64
            
            ### インストール方法
            
            1. 対象プラットフォームのファイルをダウンロード
            2. 任意のディレクトリに展開
            3. `bin/mono` を使用してアプリケーションを実行
            
            ### ライセンス
            - Mono: MIT/LGPL License
          files: |
            artifacts/mono-*/mono-*.tar.gz
          draft: false
          prerelease: false
